---
- name: install zookeeper
  hosts: pangu-zookeeper
  sudo: True
  roles:
    - pangu-zookeeper

- name: install nimbus and redis
  hosts: pangu-nimbus
  sudo: True
  roles:
    - pangu-nimbus

- name: install storm
  hosts: pangu-storm
  sudo: True
  roles:
    - pangu-storm
