---
- name: copy storm-rpm
  copy: src=apache-storm-0.9.4-1.x86_64.rpm dest=/opt

- name: install storm
  yum: name=/opt/apache-storm-0.9.4-1.x86_64.rpm state=present

- file: path=/opt/apache-storm-0.9.4/data state=directory mode="u=rwx,g=rx,o=rx"

- name: add hostname
        lineinfile: dest=/etc/hosts
                    line="{{ hostvars[item]['ipv4_addr'] }} {{item}}"
        with_items: groups['pangu-storm']

- name: add supervisor.conf
  copy: src=supervisor.ini dest=/etc/supervisord.d/supervisor.ini
  notify: Restart supervisord

- template: >
    src=storm.yaml.j2
    dest=/opt/apache-storm-0.9.4/conf/storm.yaml
    mode=644
    owner=root
  notify: Restart storm

- name: Enable 38286
  firewalld: port=38286/tcp permanent=true state=enabled
  notify: Restart firewalld

- name: Enable 6700
  firewalld: port=6700/tcp permanent=true state=enabled
  notify: Restart firewalld

- name: Enable 6701
  firewalld: port=6701/tcp permanent=true state=enabled
  notify: Restart firewalld

- name: Enable 6702
  firewalld: port=6702/tcp permanent=true state=enabled
  notify: Restart firewalld

- name: Enable 6703
  firewalld: port=6703/tcp permanent=true state=enabled
  notify: Restart firewalld




